source 'https://github.com/LovePlayModule/Podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'Recommend_Category_Example' do
  pod 'Recommend_Category', :path => '../'
  pod 'Mediator'
  target 'Recommend_Category_Tests' do
    inherit! :search_paths

    
  end
end
